---
title: "GLS"
output: html_document
---

- 前置作業
```{r}
# install package "PoEdata"
library(devtools)
install_git("https://github.com/ccolonescu/PoEdata")
```

```{r}
library(dplyr)
library(PoEdata)
library(lmtest)
library(broom)
library(sandwich)
library(stargazer)
```

## Data
```{r}
data("food")
```


## Known Form of Variance
```{r}
w <- 1/food$income

# wls
food_wls <- lm(food_exp ~ income, weights = w, data = food)

# ols
food_ols <- lm(food_exp ~ income, data = food)
```

- comparsion between wls and ols
```{r}
# gather robust standard errors in a list
rob_se <- list(sqrt(diag(vcovHC(food_ols, type = "HC1"))),
          sqrt(diag(vcovHC(food_wls, type = "HC1"))))

# generate table
stargazer(food_ols, food_wls,
  header = FALSE, 
  type = "text",
  digits = 3, 
  column.labels = c("ols", "wls"),
  dep.var.labels.include = FALSE,
  dep.var.caption = "Model Comparsion: OLS vs. WLS",
  se = rob_se)
```

## Unknown Form of Variance
```{r}
food$ehat <- (food_ols$residuals)^2
sigmahat_ols <- lm(log(ehat) ~log(income), data = food)
food$expo_sigmahat <- exp(sigmahat_ols$fitted.values)
w_sig <- 1/food$expo_sigmahat
food.fgls <- lm(food_exp~income, weights=w_sig, data=food)

# write in another way
food %>%
  mutate(
    ehat = (food_ols$residuals)^2
  ) %>%
  lm(log(ehat) ~log(income), data = .) %>%
  {1/exp(.$fitted.values)} %>%
  lm(food_exp~income, weights=., data=food) -> food_fgls2
```

- comparsion in ols, wls and fgls model
```{r}
# gather robust standard errors in a list
rob_se <- list(sqrt(diag(vcovHC(food_ols, type = "HC1"))),
          sqrt(diag(vcovHC(food_wls, type = "HC1"))),
          sqrt(diag(vcovHC(food_fgls, type = "HC1"))))

# generate table
stargazer(food_ols, food_wls, food_fgls,
  header = FALSE, 
  type = "text",
  digits = 3, 
  column.labels = c("ols", "wls", "fgls"),
  dep.var.labels.include = FALSE,
  dep.var.caption = "Model Comparsion: OLS vs. WLS vs. FGLS",
  se = rob_se)
```




## Grouped Data
