---
title: "Model Specification"
output: html_document
---

- 前置作業
```{r}
library(AER)
library(dplyr)
```

## Data
```{r}
data("CASchools")
```

- 生存師生比`STR`和平均成績`score`變數
```{r}
CASchools <- CASchools %>% 
  mutate(
    STR = students/teachers,
    score = (read+math)/2
  )
```

## Model
- 探討學生的平均成績會受到學校師生比變化怎樣的影響？其因果關係為何？
1. 先了解```score```和其他變數的關係
```{r}
# set up arrangement of plots
p <- rbind(c(1, 2), c(3, 0))
graphics::layout(mat = p)

plot(score ~ english, 
     data = CASchools, 
     col = "steelblue", 
     pch = 20, 
     xlim = c(0, 100),
     cex.main = 0.9,  # 標題放大倍數
     main = "Percentage of English language learners")

plot(score ~ lunch, 
     data = CASchools, 
     col = "steelblue", 
     pch = 20,
     cex.main = 0.9,  
     main = "Percentage qualifying for reduced price lunch")

plot(score ~ calworks, 
     data = CASchools, 
     col = "steelblue", 
     pch = 20, 
     xlim = c(0, 100),
     cex.main = 0.9,
     main = "Percentage qualifying for income assistance")
```

2. 看```score```和這幾個變數的相關係數。
```{r}
# score vs english
cor(CASchools$score, CASchools$english)

# score vs lunch
cor(CASchools$score, CASchools$lunch)

# score vs calworks
cor(CASchools$score, CASchools$calworks)
```

3. 判斷各個學生特徵變數間，是否存在共線性
- solution 1: 相關係數
```{r}
# english vs lunch
cor(CASchools$english, CASchools$lunch)

# english vs calworks
cor(CASchools$english, CASchools$calworks)

# lunch vs calworks
cor(CASchools$lunch, CASchools$calworks)
```

- solution 2: VIF
```{r}
m <- lm(score ~ STR+calworks+lunch+english, data = CASchools)
car::vif(m, digits = 3)
```

4. 設計Model
```{r}
m1 <- lm(score ~ STR, data = CASchools)
m2 <- lm(score ~ STR + english, data = CASchools)
m3 <- lm(score ~ STR + english + lunch, data = CASchools)
m4 <- lm(score ~ STR + english + calworks, data = CASchools)
m5 <- lm(score ~ STR + english + lunch + calworks, data = CASchools)
```

5. 選擇適合的Model
- 把所有模型結果合在一起看。
```{r}
library(stargazer)
stargazer(m1, m2, m3, m4, m5, digits = 3, type = "text",
          column.labels = c("m1", "m2", "m3", "m4", "m5"))
```

- 比較 AIC & BIC
```{r}
ab <- broom::glance(m1) %>% 
  tibble::add_column(., model = "STR", .before = "r.squared")

ab <- broom::glance(m2) %>% 
  tibble::add_column(., model = "STR + english", .before = "r.squared") %>%
  rbind(ab,.)

ab <- broom::glance(m3) %>% 
  tibble::add_column(., model = "STR + english + lunch", 
                     .before = "r.squared") %>%
  rbind(ab,.)

ab <- broom::glance(m4) %>% 
  tibble::add_column(., model = "STR + english + calworks", 
                     .before = "r.squared") %>%
  rbind(ab,.)

ab <- broom::glance(m5) %>% 
  tibble::add_column(., model = "STR + english + lunch + calworks", 
                     .before = "r.squared") %>%
  rbind(ab,.)

ab
```

